### ISSUE TITLE
Question: Changed station/sensor configuration or information

### ISSUE THREAD

**Issue by emiliom** [ioos/sos-injector-db#16]
How does sos-injector-db behave when information for a station (and/or its sensors) changes? For example, when the name is edited or the lat & lon are updated due to a correction or redeployment?

Does sos-injector-db check for such changes (based on get_stations.sql) and update the offering and sensor description (as shown via DescribeSensor) automatically?

One specific case of such changes is a reconfiguration of a station. For example, we have buoys that have summer and winter deployments with sets of sensor configurations that can be quite different and a new location that's not exactly the same as before. How does sos-injector-db handle a sudden (ie, from one run to the next) change in, say, what's returned by get_station_sensors.sql and therefore get_observations.sql? 

How have you -- fellow sos-injector-db users -- been handling station configuration changes?

This last point also touches on a broader issue about IOOS SOS practices. I'll send out a message about it to the ioostech list to see what others are doing, including ncSOS users, and solicit feedback.

Thanks!

**Comment by shane-axiom** [comment]
Closing this for now, https://github.com/ioos/sos-injector/issues/5 is relevant.
